apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dart-heroes
        role: frontend
    spec:
      containers:
        - name: dart-heroes
          imagePullPolicy: Always
          image: gcr.io/$PROJECT_ID/angular-heroes:latest
          ports:
            - containerPort: 80
      securityContext:
        runAsNonRoot: true
