apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-deployment
  namespace: dart-heroes
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dart-heroes
        tier: backend
        type: api
    spec:
      containers:
        - name: dart-heroes
          imagePullPolicy: Always
          image: dartheroes/aqueduct:latest
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
          ports:
            - containerPort: 8082