apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dart-heroes
        role: backend
        type: api
    spec:
      containers:
        - name: dart-heroes
          imagePullPolicy: Always
          image: gcr.io/$PROJECT_ID/aqueduct-heroes:latest
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
          ports:
            - containerPort: 8082