apiVersion: v1
kind: Pod
metadata:
  name: db-upgrade-job
  namespace: $NAMESPACE
spec:
  restartPolicy: Never
  containers:
    - name: migration-upgrade
      image: $IMAGE_NAME
      envFrom:
        - secretRef:
            name: secrets
        - configMapRef:
            name: config
      command: ["pub"]
      args: ["run", "aqueduct:aqueduct", "db", "upgrade", "--connect", "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db-service:5432/$(POSTGRES_DB)"]
