apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: $NAMESPACE
spec:
  selector:
    app: $APP_NAME
    tier: backend
    type: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432