apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: dart-heroes
    role: backend
    type: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432