apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
  namespace: $NAMESPACE
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_NAME
        role: frontend
        type: web
    spec:
      containers:
        - name: $APP_NAME
          imagePullPolicy: Always
          image: $IMAGE_NAME
          ports:
            - containerPort: $PORT
      securityContext:
        runAsNonRoot: true
